spring:
  application:
    name: chatApp

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASS}
    driver-class-name: ${DATASOURCE_DRIVER_CLASSNAME}

  jpa:
    show-sql: ${JPA_HIBERNATE_SHOW_SQL}
    generate-ddl: ${JPA_HIBERNATE_GENERATE_DDL}
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
      default_schema: ${DATASOURCE_SCHEMA}
    properties:
      hibernate:
        dialect: ${JPA_HIBERNATE_DIALECT}

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    from: ${EMAIL_FROM_USERNAME}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: false
      # mail.smtp.ssl.trust: ${EMAIL_HOST}
      mail.debug: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_SERVER_URL}
    admin:
      auto-create: true
jwt:
  secret: ${JWT_SECRET}

chat:
  secret: ${MSG_ENCRYPTION_SECRET}

msg:
  api-key: ${MSG_API_KEY}
  device-key: ${MSG_DEVICE_KEY}

cors:
  allowed-origins: ${ALLOWED_CORS_ORIGINS:http://localhost:5173,http://localhost:4000}

cookie:
  secure: ${COOKIE_SECURE:true}

cloudflare:
  r2:
    account-id: ${CLOUDFLARE_R2_ACCOUNT_ID}
    access-key: ${CLOUDFLARE_R2_ACCESS_KEY}
    secret-key: ${CLOUDFLARE_R2_SECRET_KEY}
    bucket-name: ${CLOUDFLARE_R2_BUCKET_NAME}
    public-domain: ${CLOUDFLARE_R2_PUBLIC_DOMAIN}

management:
  endpoints:
    web:
      exposure:
        include: mappings

logging:
  level:
    org.springframework.security: TRACE
