spring:
  application:
    name: chatApp

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASS}
    driver-class-name: ${DATASOURCE_DRIVER_CLASSNAME}
    hikari:
      connection-init-sql: "SELECT set_config('chat.secret', '${msg.secret}', false)"

  jpa:
    show-sql: ${JPA_HIBERNATE_SHOW_SQL}
    generate-ddl: ${JPA_HIBERNATE_GENERATE_DDL}
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
      default_schema: ${DATASOURCE_SCHEMA}
    properties:
      hibernate:
        dialect: ${JPA_HIBERNATE_DIALECT}

jwt:
  secret: ${JWT_SECRET}

msg:
  secret: ${MSG_ENCRYPTION_SECRET}

cors:
  allowed-origins: ${ALLOWED_CORS_ORIGINS:http://localhost:5173,http://localhost:4000}

cookie:
  secure: ${COOKIE_SECURE:true}

management:
  endpoints:
    web:
      exposure:
        include: mappings

logging:
  level:
    org.springframework.security: TRACE
